CNWeb-Version2/WebShop/Areas/Admin/Controllers/UserDataController.cs
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using WebShop.Models;

namespace WebShop.Areas.Admin.Controllers
{
    public class UserDataController : Controller
    {
        Shop db = new Shop();
        // GET: Admin/UserData
        public ActionResult Index()
        {
            ViewBag.user_logined = Session["user_logined"];
            ViewBag.is_logined = Session["is_logined"];
            var result = db.MEMBERs.ToList();
            return View(result);
        }

        [HttpPost]
        public ActionResult DeleteMember()
        {
            var id = new SqlParameter("@id", System.Data.SqlDbType.Int) { Value = TempData["delete_id"] };
            db.Database.ExecuteSqlCommand("DeleteMember @id", id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Filter(string filter)
        {
            ViewBag.user_logined = Session["user_logined"];
            ViewBag.is_logined = Session["is_logined"];

            //  Lọc danh sách thành viên theo vai trò
            var type = new SqlParameter("@type", filter);
            if (type.Value.ToString() == "3")
            {
                var result = db.MEMBERs.ToList();
                return View("Index", result);
            }
            else
            {
                var result = db.MEMBERs.SqlQuery("FilterMember @type", type).ToList();
                return View("Index", result);
            }
        }
    }
}

CNWeb-Version2/WebShop/Areas/Admin/Views/UserData/Index.cshtml
@model List<WebShop.Models.MEMBER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@{
    if (ViewBag.is_logined == 1)
    {
        <div class="row m-t-30">
            <div class="col-md-12">
                <!-- USER DATA-->
                <div class="user-data m-b-30">
                    <h3 class="title-3 text-center m-b-30">
                        <i class="zmdi zmdi-account-calendar"></i>Dữ Liệu Người Dùng
                    </h3>
                    <div class="table-data__tool">
                        @using (Html.BeginForm("Filter", "UserData", FormMethod.Post))
                        {
                            <div class="table-data__tool-left">
                                <div class="rs-select2--light rs-select2--md">
                                    <select class="js-select2" name="filter">
                                        <option selected="selected" value="3">Phân loại</option>
                                        <option value="1">Nhân viên</option>
                                        <option value="2">Khách hàng</option>
                                    </select>
                                    <div class="dropDownSelect2"></div>
                                </div>
                                <button class="au-btn-filter">
                                    <i class="zmdi zmdi-filter-list"></i>Lọc
                                </button>
                            </div>
                        }
                    </div>
                    <div class="table-responsive table-data">
                        <table class="table">
                            <thead>
                                <tr>
                                    <td></td>
                                    <td>ID</td>
                                    <td>Tên </td>
                                    <td>Địa chỉ</td>
                                    <td>Số điện thoại</td>
                                    <td>Vai trò</td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td></td>
                                        <td>
                                            <div class="table-data__info">
                                                <h6 id="id @item.member_id">@item.member_id</h6>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="table-data__info">
                                                <h6>@item.name</h6>
                                                <span>
                                                    <a id="name @item.member_id">@item.username</a>
                                                </span>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="table-data__info">
                                                <h6>@item.address</h6>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="table-data__info">
                                                <h6>@item.phone_number</h6>
                                            </div>
                                        </td>
                                        <td>
                                            @if (@item.role == 0)
                                            {
                                                <span class="role admin">Admin</span>
                                            }
                                            else if (item.role == 1)
                                            {
                                                <span class="role member">Nhân viên</span>
                                            }
                                            else
                                            {
                                                <span class="role user">Khách hàng</span>
                                            }
                                        </td>
                                        <td>
                                            <div class="table-data-feature">
                                                @if (item.role != 0)
                                                {
                                                    <div id="sendModal" class="modal" tabindex="-1" role="dialog">
                                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <h5 class="modal-title">Gửi thông tin</h5>
                                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                        <span aria-hidden="true">&times;</span>
                                                                    </button>
                                                                </div>
                                                                <div class="modal-body">
                                                                    <label for="message" class=" form-control-label">Gửi thông tin cho người dùng</label>
                                                                    <input type="text" id="message" placeholder="Nhap thong tin can gui" class="form-control">
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="submit" class="btn btn-primary" data-dismiss="modal">Gửi</button>
                                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <button class="item" data-toggle="modal" data-target="#sendModal" data-placement="top" title="send">
                                                        <i class="zmdi zmdi-mail-send"></i>
                                                    </button>
                                                    if (item.role != 2)
                                                    {
                                                        <div id="deletemember" class="modal" tabindex="-1" role="dialog">
                                                            <div class="modal-dialog modal-dialog-centered" role="document">
                                                                <div class="modal-content">
                                                                    <div class="modal-header">
                                                                        <h5 class="modal-title">Xóa tài khoản</h5>
                                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                            <span aria-hidden="true">&times;</span>
                                                                        </button>
                                                                    </div>
                                                                    <div class="modal-body">
                                                                        <label for="message" class=" form-control-label">Bạn có muốn xóa tài khoản nay là không?</label>
                                                                        <input id="delete_id" name="delete_id" disabled="disabled" type="hidden" />
                                                                        <input id="delete_name" name="delete_name" disabled="disabled" />
                                                                    </div>
                                                                    <div class="modal-footer">
                                                                        <button type="submit" class="btn btn-primary" onclick="DeleteMember()">Xóa</button>
                                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <button class="item" data-toggle="modal" data-target="#deletemember" data-placement="top" title="Xóa" onclick="DelMem(@item.member_id)">
                                                            <i class="zmdi zmdi-delete"></i>
                                                        </button>
                                                    }
                                                }
                                            </div>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                    <div class="user-data__footer">
                        <button class="au-btn au-btn-load">Xem thêm</button>
                    </div>
                </div>
                <!-- END USER DATA-->
            </div>
        </div>
    }
    else
    {
        <h1>Bạn phải đăng nhập bằng quyền Admin để sử dụng chức năng này</h1>
        <a href="@Url.Action("Login", null, new { area = "Sales", controller = "Login"}, Request.Url.Scheme) ">Đăng nhập ngay</a>
    }
}